export { diagram, diagramFromJson, Diagram, registerShapeFactory } from './core/diagram.js'
export type { DiagramOpts } from './core/diagram.js'
export { palettes, contrastColor, applyPalette } from './themes/index.js'
export { Shape, resolveSize } from './core/shape.js'
export type { ShapeOpts } from './core/shape.js'
export { Group } from './core/group.js'
export type { GroupOpts } from './core/group.js'
export { Connection, arrow, line, inherit, implement, compose, aggregate, depend } from './core/connection.js'
export type { ConnectionOpts, ConnectionType } from './core/connection.js'
export type { Node } from './core/node.js'
export { C4PersonShape, C4BoxShape, c4Person, c4System, c4ExternalSystem, c4Container, c4ExternalContainer, c4Component, c4Database } from './shapes/c4.js'
export type { C4ShapeOpts } from './shapes/c4.js'
export { DefaultPathBuilder, translatePath } from './core/path.js'
export type { PathBuilder } from './core/path.js'
export { parseColor } from './core/color.js'
export { generateId, resetIds } from './core/id.js'
export { renderDiagramToCanvas, renderToSvg } from './render/loop.js'
export type { RenderResult, CanvasWrapper } from './render/loop.js'
