export { diagram, diagramFromJson, Diagram, registerShapeFactory } from './core/diagram.js'
export type { DiagramOpts } from './core/diagram.js'
export { Shape, resolveSize } from './core/shape.js'
export type { ShapeOpts } from './core/shape.js'
export { Group } from './core/group.js'
export type { GroupOpts } from './core/group.js'
export { Connection } from './core/connection.js'
export type { ConnectionOpts, ConnectionType } from './core/connection.js'
export type { Node } from './core/node.js'
export { PathBuilder, translatePath } from './core/path.js'
export { parseColor } from './core/color.js'
export { generateId, resetIds } from './core/id.js'
